### ISSUE TITLE
Not loading correctly since today (8th June 2017)

### ISSUE THREAD

**Issue by Dajova** [TakosThings/Metro-for-Discord#1]
Booted up the computer today to see this on my discord theme:

[http://i.imgur.com/UCgdErt.png](http://i.imgur.com/UCgdErt.png)

Reinstalled the theme and still same, so im guessing the new update broke the theme.

**Comment by TakosThings** [comment]
Cludged together a somewhat temporary fix in 2.22.0 which is on the repo now.

Whether this fix will remain is another question since the Discord devs seem hellbent on killing themes.
