### ISSUE TITLE
Colored Status Icons

### ISSUE THREAD

**Issue by XenoPyax** [TakosThings/Metro-for-Discord#101]
I'D like to have colored Status icons instead of the white ones

**Comment by TakosThings** [comment]
Please follow the feature request template

```markdown
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]

**Describe the solution you'd like**
A clear and concise description of what you want to happen.

**Additional context**
Add any other context, screenshots or diagrams about the feature request here.
```

**Comment by XenoPyax** [comment]
**Is your feature request related to a problem? Please describe.**
I find it hard to see what a members status is so a colored seperation would be very helpful.

**Describe the solution you'd like**
I want a option in the css file that enables the colored version of the status or the white one(current) or a away to change the colors for each status manually.

**Additional context**

**Comment by tryoutuser** [comment]
I think this is what he meant:
![image](https://user-images.githubusercontent.com/35561383/61635178-2b7e3a80-acbd-11e9-9d55-66289f071525.png)

and what he want:
![image](https://user-images.githubusercontent.com/35561383/61635204-3b961a00-acbd-11e9-9824-402851c64d1f.png)

**Comment by XenoPyax** [comment]
yes it changes to white when playing a game.

**Comment by TakosThings** [comment]
Strangely it doesn't look like Discord is defining what colour to set the status indicator, they just force it white for some reason.

**Comment by XenoPyax** [comment]
So its a discord bug?

**Comment by tryoutuser** [comment]
Ah okay then, discord fault side.
