### ISSUE TITLE
Bot Tag in detailed User view 

### ISSUE THREAD

**Issue by XenoPyax** [TakosThings/Metro-for-Discord#102]
**Describe the bug**
When entering the Detailked User view by clicking on a Bot you can see that the Bot Tag is not 100% shown and is shifted downwards abit.

**Screenshots**
http://prntscr.com/ohwgpe

**Comment by tryoutuser** [comment]
This is confirmed. Happened on my side.
![image](https://user-images.githubusercontent.com/35561383/61635870-ac8a0180-acbe-11e9-8404-56b0c7f54f75.png)
