### ISSUE TITLE
Code Block Header bug

### ISSUE THREAD

**Issue by XenoPyax** [TakosThings/Metro-for-Discord#103]
**Describe the bug**
When using code block with diff it shows some extra css code before it.

**Screenshots**
http://prntscr.com/ohwhkk

**Comment by tryoutuser** [comment]
Same man. This bug has been ongoing since early v3.

**Comment by TakosThings** [comment]
This is caused by a BetterDiscord feature. Turn off 'Normalised Classes' if the option still exists.

Instructions have been added to README.md

**Comment by tryoutuser** [comment]
Okay "Normalize Classes" option in BD settings is there. This fixed it thank you.
