### ISSUE TITLE
Font size is changed on invite

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#107]
**Describe the bug**
The word invite isn't shown all the way when inviting someone to a server

**Screenshots**
![image](https://user-images.githubusercontent.com/36117192/62183924-a67ccc00-b321-11e9-8524-6a789c00837c.png)

**Comment by TakosThings** [comment]
Where about is this located?

**Comment by silent** [comment]
Go to Invite People in a server.
