### ISSUE TITLE
Voice call icon missing despite on Windows 10

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#109]
I think this bug has been around since v3.9.X maybe. I guess.

![image](https://user-images.githubusercontent.com/35561383/62879847-36753980-bd56-11e9-8696-b342cf5033fc.png)

Appears like this in DM and group DM. I am on Windows 10 v1809 b 17763.

**Comment by TakosThings** [comment]
Please use the Bug report template in future
```markdown
**Before opening an issue**
* Make sure you have updated to the latest available version.
* Try not to report multiple unrelated issues in the same submission, open new issues for them instead.

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce**
Explain the steps to reproduce the issue (if required).

**Screenshots**
If applicable, add screenshots to help explain your problem. Screenshots should have context. A 10 pixel wide image and saying "this scrollbar" is not helpful.
```

**Comment by tryoutuser** [comment]
Okay sorry. I am on latest version, v3.11.1 and using the old good rauenzi BBD.

No need to reproduce since it is a button/visual bug.

**Comment by TakosThings** [comment]
It's unusual that only one icon is missing, as they all come from the Segoe MDL2 Assets fonts.  
Possibly this could be caused by an out of date font?

As above, I've changed the icon to just a normal phone (E717 for [reference](http://modernicons.io/segoe-mdl2/cheatsheet/))

**Comment by tryoutuser** [comment]
I don't know, this is Windows stock font I have.

![image](https://user-images.githubusercontent.com/35561383/63163692-5fe0de80-c050-11e9-9bb2-b731d17a9a03.png)

**Comment by FennisOT** [comment]
The issue is also displayed on the friends tab. I also use the same settings as tryoutuser.
![missingicon](https://user-images.githubusercontent.com/14151917/63614374-e0ec2880-c5b0-11e9-91fc-4df5a5799781.png)

**Comment by tryoutuser** [comment]
confirmed it's also happened at Friends > All tab, usual list view.
