### ISSUE TITLE
Custom emojis too big, fast members' roles edit don't list all the roles

### ISSUE THREAD

**Issue by ExtraCreep** [TakosThings/Metro-for-Discord#11]
https://gyazo.com/b1b4175ed3962cfa4372b97bfb8e60f8.png Emojis bug
https://gyazo.com/9e239ba2052f633d037b36973a0e081b.png The end of my server's roles
https://gyazo.com/3d7a1590526f6a08e2288d4f041191cf.png The end of fast members' roles edit (by clicking on the member and "+" at the "Role(s)" category

**Comment by TakosThings** [comment]
> The end of my server's roles

Is this referring to the `@everyone` role background colour?

**Comment by ExtraCreep** [comment]
> Is this referring to the `@everyone` role background colour?
Yep
