### ISSUE TITLE
Profile popout opens in incorrect position

### ISSUE THREAD

**Issue by Jelexis** [TakosThings/Metro-for-Discord#111]
when you open up someone's context menu its fucking massive and even goes beyond the border
when you click it from text chat

**Comment by silent** [comment]
So we just gonna ignore those channel names.

**Comment by tryoutuser** [comment]
ni🅱🅱a wtf

**Comment by Jelexis** [comment]
ay ay ay don't judge this

**Comment by Jelexis** [comment]
this is my creation it's weird ok?
i just wanna know if that thing can be fixed or nah

**Comment by TakosThings** [comment]
Please use the Bug Report template in future
```markdown
**Before opening an issue**
* Make sure you have updated to the latest available version.
* Try not to report multiple unrelated issues in the same submission, open new issues for them instead.

**Describe the bug**
A clear and concise description of what the bug is.

**Steps to reproduce**
Explain the steps to reproduce the issue (if required).

**Screenshots**
If applicable, add screenshots to help explain your problem. Screenshots should have context. A 10 pixel wide image and saying "this scrollbar" is not helpful.
```

**Comment by Jelexis** [comment]
![image](https://user-images.githubusercontent.com/34991429/64369408-fb001f00-d024-11e9-9293-46616286e0e8.png)

I can only describe it with this image whenever I click on someone's name from chat this is what happens.
the panel is completely oversized and it goes beyond the borders

**Comment by Jelexis** [comment]
also, I am using the latest version of the theme
