### ISSUE TITLE
Discord update from 10.Sep.'19 broke various parts

### ISSUE THREAD

**Issue by second2050** [TakosThings/Metro-for-Discord#113]
**Describe the bug**
The Discord update from 10.Sep.'19 broke various parts of the theme.
These include: 
• The profile setting, mute, deaf button in the lower left corner.
• A gap between the server and channel list.
• The Discord Home Button at the top of the server list looks like it has the Home () and the Discord logo on top of each other
• The channel list has the wrong color 

**Steps to reproduce**
Use Version 3.11.2 on Discord with the update from the 10.Sep.'19

**Screenshots**
![Metro-for-Discord 10 Sep '19](https://user-images.githubusercontent.com/37344371/64596240-d1901c00-d3b3-11e9-992b-ecbf2f1b5637.png)

**Comment by TakosThings** [comment]
Closing this issue as it is superseded by #114
