### ISSUE TITLE
Pinned msg, members & mentions icons missing in other languages

### ISSUE THREAD

**Issue by TechniKris** [TakosThings/Metro-for-Discord#115]
**Description:**
Buttons for "Pinned Messages", "Member List" and "Mentions" in the top-right corner of the window have no icons when Discord is set to a different language than English (US) or English (UK).
I didn't go through all languages, but I checked a couple, both on 3.11.2 and 3.12.0 Alpha 1 (newest).

**Screenshot:**
_Example with Polish language and accent color set to #D70000_
![image](https://user-images.githubusercontent.com/30842158/65248226-20475f80-daf2-11e9-99ee-a74ef6f8fef8.png)

**Comment by TakosThings** [comment]
This is due to how the icons are selected in the CSS which relies on the English translation eg. `div[aria-label="Pinned Messages"]`.

README.md will be updated to include this as a requirement, and a warning message in the client to warn the users who ignore it.
