### ISSUE TITLE
Right click context menu clipped over title bar

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#118]
**Describe the bug**
I don't know if this theme or betterdiscord fault but I noticed this right click context menu clipped over title bar

**Steps to reproduce**
Right click at any of people or maybe bots messages to open context menu for adding reactions or copy/delete chat near / close below channel topic

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/66267587-cc13dd80-e85c-11e9-8910-8db1993afebf.png)

**Comment by second2050** [comment]
Sorry for commenting on a closed issue but on 3.12.2 it's still clipping trough the titlebar.
![image](https://user-images.githubusercontent.com/37344371/67213941-2bf2b280-f41f-11e9-8de9-3456bedee0b4.png)
I'm using BetterDiscord.

**Comment by tryoutuser** [comment]
Same here @second2050

**Comment by Starwort** [comment]
![image](https://user-images.githubusercontent.com/16487249/74888092-ea462a00-5374-11ea-8ed0-645b433f83b2.png)
Still the case on 3.13.0
@TakosThings worth reopening issue
