### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#121]
**Describe the bug**
Icons are missing

**Screenshots**
The pinned, memberlist, and mentions icon are missing. 
![image](https://user-images.githubusercontent.com/36117192/68515649-56c66e80-0247-11ea-95a1-f6de45819e47.png)

**Comment by silent** [comment]
Join voicecall and add friends to dm are now missing as well.
![image](https://user-images.githubusercontent.com/36117192/68551379-09c2d380-03d2-11ea-9f23-8029cd113a8f.png)

**Comment by Dajova** [comment]
Latest Discord version seems to also have removed a few other icons
![discord](https://i.imgur.com/i50utld.png)
