### ISSUE TITLE
3.13.0

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Metro-for-Discord#133]
List of issues

**Outstanding Issues**
- [x] #130 
- [x] #131

**New Issues**
- [x] Chatbox ⚠
- [x] Remove chat message hover state
- [x] Decrease font-weight of chat usernames
- [x] Chat options menu is mis-aligned
- [x] Home friends list
- [x] Remove `/popout/_chat_options.scss`
- [x] Some User Settings sidebar menu options have wrong icons
- [x] Move theme version number in User Settings from bottom right to Discord's version no. under the logout button
- [x] Chat scrollbar showing both up/down arrows
- [x] Chat file attachments
- [x] Recent mentions popout

⚠ = Priority

Changes will be made in the 3.13.0 branch. Advanced users may clone and build a preview for their own use. Everyone else should use the available pre-releases.

**Comment by TakosThings** [comment]
Pre-release 1 available from [Releases](https://github.com/TakosThings/Metro-for-Discord/releases/tag/v3.13.0-pre1).

**Issues addressed**
* Chatbox
*  Remove chat message hover state
 * Decrease font-weight of chat usernames
 * Chat options menu is mis-aligned
* Some User Settings sidebar menu options have wrong icons
* Move theme version number in User Settings from bottom right to Discord's version no. under the logout button

**Comment by silent** [comment]
The spacing between a message and the chatbox needs to be adjusted as right now it's a bit too close to my liking than it was before. 
![image](https://user-images.githubusercontent.com/36117192/73789706-e2776a80-4764-11ea-961c-40d57aec7b42.png)

**Comment by silent** [comment]
> /* remove the three emojis in the message menu */
.emojiButton-jE9tXC.button-1ZiXG9, .emojiSeparator-10VgEJ.separator-42rNt0 {
    display: none;
}
/* scale down the menu buttons, transparent background is optional */
.wrapper-2aW0bm {
    background-color: transparent;
    transform: scale(0.75)
}
/* move the menu buttons down to align with the message */
.buttons-cl5qTG {
    transform: translateY(21px);
}
/* move the buttons down even more for the first message in a message group */
.message-2qnXI6 > h2 + .markup-2BOw-j + .container-1ov-mD + .buttonContainer-DHceWr > .buttons-cl5qTG {
    transform: translateY(35px);
}
/* add margin at the right so that the menu buttons don't cover text */
.markup-2BOw-j {
    margin-right: 60px;
}

This is helpful in terms of fixing many issues this update has caused including the one I put above.

**Comment by TakosThings** [comment]
> The spacing between a message and the chatbox needs to be adjusted as right now it's a bit too close to my liking than it was before.

Agreed, chat spacing in general is just awful. This will probably make up the entirety of changes in Pre2

**Comment by TakosThings** [comment]
Pre-release 2 available from [Releases](https://github.com/TakosThings/Metro-for-Discord/releases/tag/v3.13.0-pre2).

**Issues addressed**
* Added bottom margin to increase gap between chatbox and last message
* Increased left padding on toolbar channel name
* Many sizing and position fixes for chat
* Added border lines back to cozy and compact chat modes to assist with chat legibility
* Changed emoji picker category icons to MDL2
* New server modal
* Remove `/popout/_chat_options.scss`

**In progress**
* Friends list - still lots to do here

**Comment by TakosThings** [comment]
Pre-release 3 available from [Releases](https://github.com/TakosThings/Metro-for-Discord/releases/tag/v3.13.0-pre3).

**Issues addressed**
* Remove Nitro link from Friends conversation list as clicking it breaks the client until restart
* Remove some duplicate CSS related to badges
* Fix compact and cozy chat indenting
* Friends table
* Scrollbars showing both arrow buttons
* Some minor style changes to the members list

**Comment by silent** [comment]
I noticed there is a theme issue with changing server regions on a server.
![image](https://user-images.githubusercontent.com/36117192/73972393-6442d180-48e6-11ea-9c55-94898d04fa34.png)
