### ISSUE TITLE
[reopen] Title bar / context menu clipping issues

### ISSUE THREAD

**Issue by Starwort** [TakosThings/Metro-for-Discord#137]
**Describe the bug**
Reopen of #118 as bug still in latest theme version [3.13.0]

**Steps to reproduce**
Open a context menu near the top of the Discord screen and hover over a submenu to extend it above the screen (add reaction works easily)

**Screenshots**
![tryoutuser's screenshot](https://user-images.githubusercontent.com/35561383/66267587-cc13dd80-e85c-11e9-8910-8db1993afebf.png)  
(credit tryoutuser, #118)
![second2050's screenshot](https://user-images.githubusercontent.com/37344371/67213941-2bf2b280-f41f-11e9-8de9-3456bedee0b4.png)  
(credit second2050, #118)
![my image](https://user-images.githubusercontent.com/16487249/74888092-ea462a00-5374-11ea-8ed0-645b433f83b2.png)  
(my image, #118)

**Comment by tryoutuser** [comment]
can confirm it's happened again. clipped over title bar.

**Comment by TakosThings** [comment]
Had to revert the the commit referenced above. This is an especially annoying one to figure out, so no fix for this one in v1.13.1.

Side note
Meanwhile at Microsoft: "what are design standards"
![start](https://user-images.githubusercontent.com/20344790/75580150-2ab15080-5ab7-11ea-8743-d0d796b7d53d.png)
![taskbar](https://user-images.githubusercontent.com/20344790/75580153-2c7b1400-5ab7-11ea-8fab-5251135e682d.png)

**Comment by tryoutuser** [comment]
lmao holy shit yeah 😂
