### ISSUE TITLE
Spacing breaks when jumping to a message

### ISSUE THREAD

**Issue by Starwort** [TakosThings/Metro-for-Discord#141]
**Describe the bug**
Jumping to a message makes the vertical spacing weird

**Steps to reproduce**
Jump to a message using ctrl-f

**Screenshots**
![image](https://user-images.githubusercontent.com/16487249/75585835-eac47c00-5a6a-11ea-827a-a4e4dba214f7.png)
![image](https://user-images.githubusercontent.com/16487249/75585870-ff087900-5a6a-11ea-9dd7-03193e91f043.png)

**Comment by snappyapple632** [comment]
I found a very similar issue with the "New Message" bar pictured in this screenshot:
![newoffset](https://user-images.githubusercontent.com/40573129/75613030-f9984680-5add-11ea-86d9-a16d0dad7aca.PNG)

**Comment by tryoutuser** [comment]
can confirm from @snappyapple632 's comment. new indicator also get bugged
