### ISSUE TITLE
Issues with Custom Statuses

### ISSUE THREAD

**Issue by Jelexis** [TakosThings/Metro-for-Discord#147]
**Describe the bug**
Incorrect or Oddly placed Custom Status When clicking on someone's name and When clipping in text when setting a Custom Status
**Steps to reproduce**
When clicking on your or other's names and when setting a custom status

**Screenshots**
![image](https://user-images.githubusercontent.com/34991429/78016606-b686f880-7353-11ea-941b-33986693dd58.png)
I am not sure if this is a bug or not but i believe it is. the placement looks off and when setting a long status it looks messy and even messes with long names. it's shown in next picture
![image](https://user-images.githubusercontent.com/34991429/78017001-49279780-7354-11ea-936c-f9afe937fcae.png)

Next is when setting a custom status, the emote icon is clipping with the beginning of the text line
which blocks view of first and second word. 
![image](https://user-images.githubusercontent.com/34991429/78017222-9a378b80-7354-11ea-85db-7b69e44de78e.png)

**Comment by TakosThings** [comment]
Theese will be resolved in v3.14.0.

In progress shot:
![image](https://user-images.githubusercontent.com/20344790/78096454-24e5bc80-7421-11ea-85a4-c4e7c2dc41ce.png)

**Comment by tryoutuser** [comment]
confirmed. it's really weird.
