### ISSUE TITLE
Emote categories bug

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#15]
I noticed this 3 days ago. After quit and relaunch discord, this happen.
I don't know what discord upstream updates did, suddenly I can't switch in between Twitch, Favorites and Emoji tabs.

I am using Zere's BD fork, and just updated to v3.4.2 of this theme.

- https://x0.at/R6F.jpg

See that those 3 tabs is overridden by emotes right when I click Emoji tab. Can't switch back to Twitch or Favorites.

**Comment by TakosThings** [comment]
This should be fixed. v3.4.3 is now available.
