### ISSUE TITLE
Having issue here?

### ISSUE THREAD

**Issue by tjw0lf** [TakosThings/Metro-for-Discord#150]
I don't have any of the icons in the Top or for settings. just get squire box like this.

<a href="https://imgur.com/vLVxxb6"><img src="https://i.imgur.com/vLVxxb6.png" title="source: imgur.com" /></a>

I'm running this theme on Linux. So not sure if i need to grab something else?

**Comment by TakosThings** [comment]
You can acquire the Segoe fonts from [Microsoft Docs](https://docs.microsoft.com/en-us/windows/uwp/design/style/segoe-ui-symbol-font)

**Comment by tjw0lf** [comment]
Thank you very much i grab those fonts. Awesome theme i love it. 
I'm still getting some blocks like that in user settings,  
-Notifications 
-Linux Settings
-plugins
-Gift inventory
Those are all the ones still have blocks. All the rest are good.
