### ISSUE TITLE
Acrylic background doesn't load

### ISSUE THREAD

**Issue by tjw0lf** [TakosThings/Metro-for-Discord#151]
I took a look at the wiki here
https://github.com/TakosThings/Metro-for-Discord/wiki/Acrylic

But have no background image coming up at all even the default one? How can i get background image to come up.

**Comment by TakosThings** [comment]
If the default background image doesn't display out of the box, this could indicate there's a plugin (or another theme) causing a conflict or there may be something on the network blocking imgur.

Check the Developer Tools console and see if there's any errors related to the image being logged.

The support channels on the BetterDiscord servers may be of more help.

**Comment by tjw0lf** [comment]
where do i go for Developer Tools console,

**Comment by tryoutuser** [comment]
simply press `Ctrl + Shift + I` just like you open inspect element on browsers
