### ISSUE TITLE
Voice icons bugged

### ISSUE THREAD

**Issue by Jackaroo05** [TakosThings/Metro-for-Discord#154]
![DiscordCanary_hkRAvxTbus](https://user-images.githubusercontent.com/22356378/80007586-6ef81600-8494-11ea-961c-7794ed52116c.png)
Voice Icons bugged over to left due to go live button.
Latest version- just installed- no changes other than color and background

**Comment by Jackaroo05** [comment]
Ok so I fixed it. Just had to play around with the placement and size of things. Here's the updated file (with my colors and background- feel free to change them)
[TakosThings Metro For Discord Theme Fixed.zip](https://github.com/TakosThings/Metro-for-Discord/files/4525878/TakosThings.Metro.For.Discord.Theme.Fixed.zip)

**Comment by tryoutuser** [comment]
still considered as a bug for others

**Comment by Jackaroo05** [comment]
How so?
