### ISSUE TITLE
No Name

### ISSUE THREAD

**Issue by machmar** [TakosThings/Metro-for-Discord#155]
I dont see my name next to my profile pic.

**Comment by TakosThings** [comment]
Could you elaborate on this?

If you mean the avatar found at the bottom of the servers list, then this is a feature of the theme. If you need to copy your username and discriminator to send a friend, you can copy it from the User Settings window under the _My Account_ heading.

**Comment by machmar** [comment]
Oh, well thats that. Also btw, where are the buttons to go live and to share camera ?

**Comment by TakosThings** [comment]
It looks like they're testing new features/UI flows currently, so things may be different for other people. 

For myself (if I'm not playing a game) I need to click the voice channel I'm connected to reveal a UI similar to that of the video call to active screen share. There are controls at the bottom to control camera and screen share.

**Comment by machmar** [comment]
oh yea true
