### ISSUE TITLE
Bug/change to the now combined GIF and emoji picker

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#156]
Using v3.14.3

**Describe the bug**
I'm not sure how do i put this, bug or change request.
Straight look to the screenshot provided.
I know the popup panel is resizable, but there are a lot of empty spaces. Taken per 03 May 2020.
In anyhow or ways, could you figure out to bring back twitch and favorited twitch emoji tabs?
Just reply "cannot" or "beyond my reach" then i will ask about the twitch tab to BBD server for help.

**Steps to reproduce**
Open the "now combined" GIF and emoji picker by clicking emoji button

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/80891454-4838ab80-8cee-11ea-8249-701e73779d61.png)

**Comment by TakosThings** [comment]
The missing Twitch buttons are _probably_ a BBD issue.

I'm also not in on this A/B test so I'll have to wait until one of my accounts get it to work on this feature.

**Comment by tryoutuser** [comment]
Alright thank you.
