### ISSUE TITLE
Overall Performance

### ISSUE THREAD

**Issue by Aeswere** [TakosThings/Metro-for-Discord#157]
Is low performance/framerate a valid issue? Scrolling through messages and opening Discord's settings seems extremely slow and off-putting for me.

Unrelated note: I really like the way the theme looks.

**Comment by tryoutuser** [comment]
Same for me, it lags when i try to open settings and this has been going on since the theme born afaik.

**Comment by TakosThings** [comment]
Some of this will have been addressed in 3.14.4 by greatly reducing the area of the blur effect.

The problem with lagging when opening the Settings UI is down to how many new elements are drawn at once.  Keep in mind the main UI is also being animated at the same time.

These are some options I'll probably implement in the next update.
* Change the background the theme is shipped with to a 'gradient' background [something like this one](https://w.wallhaven.cc/full/0q/wallhaven-0qpo2q.png). This means the blur filter can be commented out unless the user needs it on for their own background.
* Add an option to remove the scale transition for the main UI when settings is opened. This means User Settings will have a simple fade in transition instead.

**Comment by tryoutuser** [comment]
Understood. After updated to v3.14.4 i see less lags now, though it's still there for a brief miliseconds but that is due UI being drawn.
