### ISSUE TITLE
Ways to hide/remove new blocked indicator?

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#159]
Updated to v3.14.4

**Describe the bug**
Not clearly a bug, i wanted to know is there a way to hide/remove new blocked indicator?

**Steps to reproduce**
To do with blocked messages indicator

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/83065356-90e54980-a08d-11ea-839c-0fbfa2a7df85.png)

**Comment by TakosThings** [comment]
No, sadly. Most that can be done is remove the text, but leaves a blank gap between messages.

**Comment by tryoutuser** [comment]
GDI fookin discord making it hard.
