### ISSUE TITLE
Reaction minor issue

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#16]
Reporting a minor issue.
I'm using latest version, v3.6.3 with original BetterDiscord.
Add reaction emoji picker window floating not near add reaction button, screenshots:

- https://x0.at/4B8.jpg
- https://x0.at/HYF.jpg

This has been broken since v3.6.1 if I remember correctly.

**Comment by TakosThings** [comment]
Partially fixed. Opening the picker from the right options menu will require further research when I get the time.

**Comment by tryoutuser** [comment]
Ok updated to v3.6.4, and yes clicking add reaction from the right side of chat still goes to the center.
- https://x0.at/caf.jpg
Existing reaction:
- https://x0.at/tdQ.jpg

Also you forgot to add meta tags for new version.
`//META{"name":"Metro_for_Discord","description":"Based on Microsoft's Modern Design Language, aka 'Metro'. Github: github.com/TakosThings","author":"Tako","version":"3.6.4"}*//{}`

**Comment by tryoutuser** [comment]
Found another one bug.
This is when I click on a user's name on the chat:
- https://x0.at/P6t.png

Not clicking from welcome/join text that generated automatically.

**Comment by tryoutuser** [comment]
Update for v3.7.1: emoji picker for existing reaction went to top right corner again.

**Comment by TakosThings** [comment]
As referenced above, a speculative fix has been produced and will be out when v3.7.2 is built.
