### ISSUE TITLE
Pinned Messages bar does weird animation when extending

### ISSUE THREAD

**Issue by Fuhsahd** [TakosThings/Metro-for-Discord#163]
**Describe the bug**
When you open the Pinned Messages it pops out really far then snaps back to the edge.

**Steps to reproduce**
Just click pinned messages button.

**Screenshots**
![image](https://user-images.githubusercontent.com/30512384/84607437-429cbc80-ae7b-11ea-85ec-beef8766c2e7.png)
![image](https://user-images.githubusercontent.com/30512384/84607445-47fa0700-ae7b-11ea-8eb0-7c5e953e6417.png)

**Comment by TakosThings** [comment]
It's a known problem that can't be fixed.
