### ISSUE TITLE
You cannot download files

### ISSUE THREAD

**Issue by ImmyShack** [TakosThings/Metro-for-Discord#164]

**Comment by ImmyShack** [comment]
Screenshot:
![Screenshot_25](https://user-images.githubusercontent.com/66964664/84692627-798bd480-af46-11ea-936c-d96a0ceddbce.png)

You cannot download files (for example zip files) when you're using the theme.

**Comment by TakosThings** [comment]
I can't replicate any issue here.

Clicking the filename will open a new browser window/tab which will handle the download, since the Discord client can't do it itself.

**Comment by ImmyShack** [comment]
> I can't replicate any issue here.
> 
> Clicking the filename will open a new browser window/tab which will handle the download, since the Discord client can't do it itself.

oh thanks!
