### ISSUE TITLE
Me and a friend are working on updated icons for this so people without Segoe MDL2 can use the skin.

### ISSUE THREAD

**Issue by samm-sepi0l** [TakosThings/Metro-for-Discord#166]
Takos is there anyway you can send me the new css code? Or is there anyway that I can see for myself what exactly in the file is new? I would like to port it over to our file without having to mess up the new icons. It's alright if you don't want to, just wondering. Here's a little screenshot of what we've updated. A lot of it is obviously the same since we're still working on it.
![Capture](https://user-images.githubusercontent.com/48124040/85922343-f2baee00-b89b-11ea-8d5d-ae2905cfc304.PNG)

**Comment by tryoutuser** [comment]
bruh looks epic!

**Comment by TakosThings** [comment]
All resources for the theme are available on the repo.

Microsoft makes at least version 1.60 (the latest in Windows 10 being 1.75/1.78) of the MDL2 Assets Font available from Microsoft Docs: https://aka.ms/SegoeFonts. These fonts will work on Mac and Linux.

There's currently an open issue to have the link updated to the latest on the MicrosoftDocs repo, so I'd recommend you +1 that issue so it comes to their attention.
