### ISSUE TITLE
Discord updated members/users list element

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#168]
Using v3.14.7

**Describe the bug**
Seems discord updated/changed something for members/users list column. I noticed background color change, different from chat and channels column/window. If the guild/server has small members, a crop or end can be seen.

**Steps to reproduce**
Visible if you take a look. Scroll to the end in a server that has <10 or <20 members.

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/86377994-4ae65b80-bcb3-11ea-919d-1001d2135f36.png)

**Comment by TakosThings** [comment]
May have forgotten to open the PR for this... 3.14.8 is up now
