### ISSUE TITLE
[Request] Add support for PermissionsViewer

### ISSUE THREAD

**Issue by ente3000** [TakosThings/Metro-for-Discord#17]
I'd like to request support for the [PermissionsViewer](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/PermissionsViewer) plugin, because this happens when you click on a user and the plugin is enabled:

![image](https://user-images.githubusercontent.com/8181990/37169541-7be6fbdc-2308-11e8-8c9f-57e520639dc9.png)

I'm using BetterDiscord. Probably not relevant, but I thought I'd better include it anyway. Thanks in advance!

EDIT: This also happens when the plugin is disabled and you click on someones name in the chat log (clicking on the profile image works fine though, for some reason).

**Comment by ente3000** [comment]
Thanks for the quick fix, this still happens when clicking on someones name though (red areas are censored)...
![unbenannt](https://user-images.githubusercontent.com/8181990/37217525-103c2824-23be-11e8-9bdc-0d06bdd11682.png)

**Comment by TakosThings** [comment]
Annoying to narrow down, but this should be fixed in 3.6.6.
