### ISSUE TITLE
Broken theme since latest version.

### ISSUE THREAD

**Issue by Dajova** [TakosThings/Metro-for-Discord#174]
**Before opening an issue**
* Make sure you have updated to the latest available version.
* Try not to report multiple unrelated issues in the same submission, open new issues for them instead.

**Describe the bug**
The theme does not work at al since the latest version. Updated python to 3.8.5, updated pip to 20.2.1, reapplied theme, still same. Was fine before this version.
Tried to reapply theme and restarting computer, still doesn't work.

**Steps to reproduce**
Simply updating Discord to latest version breaks it.

**Screenshots**
---

**Comment by TakosThings** [comment]
BeautifulDiscord issue - see https://github.com/leovoel/BeautifulDiscord/issues/90

**Comment by TakosThings** [comment]
BeautifulDiscord has been updated. Reapply patch as normal.

Theme update also available from [releases](https://github.com/TakosThings/Metro-for-Discord/releases/latest)
