### ISSUE TITLE
UI Shifts left when changing tabs in the inbox popout

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Metro-for-Discord#190]
**Describe the bug**
Discord UI shifts left when opening the Inbox popout, and doesn't return when closed.

Work around: Close and reopen the inbox popout to resolve.

**Steps to reproduce**
* Method A: Open the inbox popout, then alt+tab or unfocus the Discord window
* Method B: Open the inbox poput, then change to the Unreads (or Mentions) tab

**Screenshots**
![image](https://user-images.githubusercontent.com/20344790/99351671-03bed700-28f1-11eb-845a-a46129031dfd.png)

**Comment by My-Name-Is-Adam** [comment]
Any update on this, please? 
Still happening for me.

**Comment by My-Name-Is-Adam** [comment]
![image](https://user-images.githubusercontent.com/44755101/104988897-25cbf700-5a11-11eb-9c9a-c237c66898ca.png)
This is still happening. I also am unable to type in the channels as it doesn't show the box.

**Comment by TakosThings** [comment]
Update to latest version

**Comment by My-Name-Is-Adam** [comment]
I already have. 
Metro for Discordv3.15.5by Tako? Is that right?

**Comment by TakosThings** [comment]
The latest version is 3.15.6, download it from the releases page, as per usual.

**Comment by My-Name-Is-Adam** [comment]
That is the version I downloaded and was using. My apologies. Clearing cache fixed this. 

Disabling the Channel Tabs plugin lets me type in channels now.  Can you make this theme compatible with the Channel Tabs plugin, please? Thank you.

**Comment by TakosThings** [comment]
> Can you make this theme compatible with the Channel Tabs plugin, please? Thank you.

I'm not currently working on maintaining BD plugins (See #192). There was work done in 3.15.0 to make it easier for plugin CSS to be added if people are interested.
