### ISSUE TITLE
Re-Implementation of Discord's "Find a Conversation" search bar.

### ISSUE THREAD

**Issue by StarmanInDisguise** [TakosThings/Metro-for-Discord#193]
Hello,

Please correct me if this is an unintended bug or not, but I think this Theme would very much benefit from the re-implementation of Discord's "Find a Conversation" search bar. I use this to engage in DM's with people I dont have friended most of the time, or even as a means to find someone in my long list of recent conversations. I've noticed that I've had to switch my theme back to default in order to access the UI element necessary to access the feature.

**Comment by KibSquib48** [comment]
you can use Control + K on Windows/Linux or Command + K on macOS, pulls up the same menu

**Comment by TakosThings** [comment]
> you can use Control + K

Pretty much this. There was a reminder in the toolbar that `ctrl+k` opens the search, but was removed in 3.10.0 as they were pushing the quickswitcher pretty hard.

Can look in to adding a reminder again somewhere in the friends list if people want it again.
