### ISSUE TITLE
Background 

### ISSUE THREAD

**Issue by spartaque12** [TakosThings/Metro-for-Discord#195]
**Is your feature request related to a problem? Please describe.**
background is too small

**Describe the solution you'd like**
make a option, or just ability to fully change background image, not just left side

**Additional context**
this area too (red square)
![2020-11-29 1-43-19](https://user-images.githubusercontent.com/6484816/100528352-8f374280-31e4-11eb-94ac-6794ae9f268c.png)

**Comment by TakosThings** [comment]
The background for acrylic is intended to only be visible on the left pane, and title/toolbar of theme.

I'm not really interested in adding to the pile of transparent themes, as they're just a headache to use and maintain.
