### ISSUE TITLE
Discord server banner is a little bit out of place

### ISSUE THREAD

**Issue by MazeWave** [TakosThings/Metro-for-Discord#198]
**The bug**
I don't know if this is intended but banners are a little out of place

**Steps to reproduce**
Go to any server that has a banner

**Screenshots**

![image](https://user-images.githubusercontent.com/25009364/101518581-66504380-3982-11eb-943b-dc6abad0f3c7.png)

**Comment by TakosThings** [comment]
It's intentionally like this. There are often visibility issues when the banner spans the the guilds list as well.
