### ISSUE TITLE
Tiny Spotify issue that slipped by me.

### ISSUE THREAD

**Issue by iKatt** [TakosThings/Metro-for-Discord#20]
Didn't notice this one. Doesn't fit the theme either. Sorry for not including it in the last issue.

![image](https://user-images.githubusercontent.com/10321978/37394563-2d4993e4-27c8-11e8-9bf2-c127e9a1914e.png)

**Comment by TakosThings** [comment]
> Screenshots must include context. A 10px wide image and saying "This scrollbar" is not helpful at all
Where is this located?

**Comment by iKatt** [comment]
Sorry, updated the image.

**Comment by TakosThings** [comment]
Closing and marking as ongoing. I'll fix the issue if I come across the dialog at some point in the future.
