### ISSUE TITLE
Light theme

### ISSUE THREAD

**Issue by maicol07** [TakosThings/Metro-for-Discord#203]
**Is your feature request related to a problem? Please describe.**
Currently the theme only supports Discord Dark

**Describe the solution you'd like**
A Metro Light theme

**Comment by JeremixxGithub** [comment]
Hello! I have the same problem here. Fortunately, I have found a perfect solution to it, and it might be the .theme-light compnents. 

You should probably copy the .theme-dark components and change the colors to the light mode ones.

Thank me later if I helped you.

**Comment by maicol07** [comment]
Thank you. Do you know the colors HEX for the light theme?

**Comment by TakosThings** [comment]
I'm not really interested in working on a light theme at the moment.

Though if *you* are you should be looking at [`core/_variables.scss`](https://github.com/TakosThings/Metro-for-Discord/blob/master/src/components/core/_variables.scss). This is where *almost* all colours are defined. Don't edit the CSS files you get from releases.

I try and base as much as I can on the WinUI Figma Toolkit which you find on [Microsoft Docs](https://docs.microsoft.com/en-gb/windows/uwp/design/downloads/).
After importing the Figma toolkit you'll be able to see a list in the right pane of colours used the project.
![image](https://user-images.githubusercontent.com/20344790/107145750-9cff0600-6993-11eb-9852-9ad2bc6bfc6a.png)
