### ISSUE TITLE
Share Screen And Turn on camera mess up with Channels And Vc-Channels

### ISSUE THREAD

**Issue by enzomtpYT** [TakosThings/Metro-for-Discord#206]
* Make sure you have updated to the latest available version.
-Checked (Installed Yesterday)

* Try not to report multiple unrelated issues in the same submission, open new issues for them instead.
-Checked ( 5 Minutes ago )

**Describe the bug**
The buttons of Turn on camera and Share Screen are broken : they go out of the "box of buttons"

**Steps to reproduce**
-Install Discord
-Install BetterDiscord
-Install theme
-Go in Vc
-Install Disc
-See the bug with Turn on camera and Share Your screen icon goes out of "buttons box"

**Screenshots**
![image](https://user-images.githubusercontent.com/40535918/108504368-0c3ef900-72b6-11eb-93c4-7424d8e95732.png)
![image](https://user-images.githubusercontent.com/40535918/108504949-fd0c7b00-72b6-11eb-8fb4-9fb86135fa03.png)

**Comment by TakosThings** [comment]
This comment is just for tracking. Reference 57016b2
