### ISSUE TITLE
Webcam icon missing on redesigned RTC contols

### ISSUE THREAD

**Issue by snappyapple632** [TakosThings/Metro-for-Discord#208]
**Describe the bug**

The icon for the "Turn On Webcam" button is missing.

**Screenshots**
![Screenshot 2021-02-19 222603](https://user-images.githubusercontent.com/40573129/108616601-932dc780-73c3-11eb-85c4-372dadbefe02.png)

**Comment by TakosThings** [comment]
Try this as a temporary fix: Find the below in the CSS file:
```
.theme-dark .container-1giJp5 button[aria-label^=Camera]::before
```
and replace it with:
```
.theme-dark .container-1giJp5 button[aria-label*=Camera]::before
```

**Comment by snappyapple632** [comment]
The fix works great. Thank you!
