### ISSUE TITLE
Icons not showing 

### ISSUE THREAD

**Issue by ReformedNemesis** [TakosThings/Metro-for-Discord#209]
Hi, i've just installed your theme and i noticed that no icons have been showing.. i've tried to restart discord and stuff but none of the things i did seemed to work
https://i.imgur.com/YCW4arK.png

**Comment by TakosThings** [comment]
What OS are you running? Judging from the screenshot you don't have either Segoe UI or Segoe MDL2 Assets, both of which should be installed by default on Windows 10.

**Comment by TakosThings** [comment]
Inactive - closing.
