### ISSUE TITLE
Message on users after clicking their icon has a different skin.

### ISSUE THREAD

**Issue by iKatt** [TakosThings/Metro-for-Discord#21]
![image](https://user-images.githubusercontent.com/10321978/37697788-ef26d0ac-2d32-11e8-8219-7894de4182b8.png)

Recent update onto PTB causes this little issue where the arrow is pointing.

**Comment by TakosThings** [comment]
Already fixed in https://github.com/TakosThings/Metro-for-Discord/commit/987e4bc6aed826f296a884c448d6d43603b0106a, and will be included in the next build

**Comment by tryoutuser** [comment]
it's not just canary/PTB, also on stable version
