### ISSUE TITLE
Theme doesn't appear in BetterDiscord

### ISSUE THREAD

**Issue by RustedNotFound** [TakosThings/Metro-for-Discord#212]
**Describe the bug**
Cant add to discord. I added your theme before but I ran into issues and had to uninstall discord and reinstall while reuploading betterdiscord and going to themes It wont let me add yours. I have windows 10 and everything but this time it wont work

**Comment by TakosThings** [comment]
I edited your issue to make it easier to read, be sure to use the issue template!

Make sure you download the correct CSS file from the [Releases ](https://github.com/TakosThings/Metro-for-Discord/releases/latest) page. For BetterDiscord, only `Metro_for_Discord.theme.css` will work. 

![image](https://user-images.githubusercontent.com/20344790/111944696-2a537f80-8b28-11eb-8352-6a486bf045b7.png)

*Don't* clone the repo or download the 'Source Code' zip or tar.gz files, unless you're a developer.

**Comment by TakosThings** [comment]
Closing, inactive
