### ISSUE TITLE
BeautifulDiscord issue

### ISSUE THREAD

**Issue by Dajova** [TakosThings/Metro-for-Discord#213]
**Describe the bug**
Seems to be semi-broken since latest Discord update, with BeautifulDiscord. Uninstalling/reinstalling/update of the program nor theme fixes it.

**Steps to reproduce**
See above.

**Screenshots**
![image](https://i.imgur.com/MCh8QLB.png)
As you can see, icons are overlapping eachother and they have been revered back to default. Plus, the server selection is uninteractiable.

**Comment by TakosThings** [comment]
Looks like this is just a class reroll.

I won't be able to update this till later today. Press ctrl + comma to open Settings (if you can't use the button) to disable the theme for now.
