### ISSUE TITLE
Please Add German Language without Red Banner

### ISSUE THREAD

**Issue by velotoxicsounds** [TakosThings/Metro-for-Discord#216]
Please Add German Language without Red Banner 
"This theme requires English to be the selected Language. Press 'CTRL + comma' to open your settings.";

**Comment by TakosThings** [comment]
I'm not really sure it's possible/feasible to do support for all languages. My rough math says there would be about 60 icons needing localisations, and with 28 languages... the list grows quickly.

Best way I can think of doing this would be creating addon files for each language which users would run along side the main theme. Though this wouldn't work with BeautifulDiscord, and I'd prefer to keep both versions of theme as close as possible.

Either that or I venture into the realm of creating a theme customiser site on gh-pages...

I'll do some experimenting, also happy to other's thoughts/ideas.

**Comment by KaKi87** [comment]
Hello from France,

May I ask why, while all other BetterDiscord themes I ever used never depended on language, yours does ?

This is really constraining, especially considering that setting is synced across all devices on Discord.

Thanks.

**Comment by TakosThings** [comment]
> May I ask why, while all other BetterDiscord themes I ever used never depended on language, yours does ?

It's due to the icon replacements. The most reliable way to do this is by selecting elements using the `aria-label`s. Since the `aria-label` exists for accessibility the value changes depending on the user's language.

I'm working on fixing this in Fluent Discord. Depending on how fast development is on Fluent it'll probably be ported back here to Metro.

**Comment by KaKi87** [comment]
Oh, I didn't know there was a *Fluent for Discord*.
What are the differences between *Metro* and "Fluent*, and how can I try that other one ?
Thanks

**Comment by TakosThings** [comment]
It's in development, so everything is only half done. The repo is pinned on my profile.

**Comment by KaKi87** [comment]
I see, good luck !
