### ISSUE TITLE
Bot indicator

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#22]
Noticed this bug since v3.7.4 after discord introduced `@someone` feature.
I'm using latest version, 3.7.5 with BetterDiscord
Screenshot:
https://x0.at/ytV.jpg

**Comment by tryoutuser** [comment]
Just happens today
- https://x0.at/oPb.jpg
Search bar bug

**Comment by TakosThings** [comment]
Moved search popout issue to #23
