### ISSUE TITLE
BandagedBD v1.0.0 update broke settings

### ISSUE THREAD

**Issue by enzomtpYT** [TakosThings/Metro-for-Discord#220]
* Make sure you have updated to the latest available version.
Yes i have the lastest
* Try not to report multiple unrelated issues in the same submission, open new issues for them instead.
Nope checked 1 second ago

**Describe the bug**
When i updated BandagedBD to 1.0.0 all BBD settings were bugged

**Steps to reproduce**
Update BandagedBD
See problem in settings

**Screenshots**
![image](https://user-images.githubusercontent.com/40535918/113337190-b97e4580-9327-11eb-9a70-77aa5370eeeb.png)

**Comment by MarshallYTHD** [comment]
I have the same problem but mine says "Stable 81297 (454fb5e)" instead and I updated using [BetterDiscord's installer](https://github.com/BetterDiscord/Installer).

**Comment by NicciZar** [comment]
Same
![image](https://user-images.githubusercontent.com/43537611/113476295-f60e8600-947a-11eb-95e3-5664961335f2.png)

**Comment by NicciZar** [comment]
The newest version seems to be working for me
![image](https://user-images.githubusercontent.com/43537611/113707753-a7fabc00-96e0-11eb-8c66-30175cb58955.png)

**Comment by tryoutuser** [comment]
looks okay enough i couldn't care for icons at this point. new BBD really broke some parts.

![image](https://user-images.githubusercontent.com/35561383/114154249-62d9c280-994a-11eb-84aa-03f05a457add.png)

Steph if you built it using a new segoe UI emoji font version please reply! thank you!

**Comment by TakosThings** [comment]
This is fixed in 4af55d7720ce75987f14baaa42ea07d6a949a5cc. I just haven't done the 3.15.12 build yet. Should be out shortly.

**Comment by andrew071117** [comment]
![image](https://user-images.githubusercontent.com/81406482/117067791-72092180-acf8-11eb-8e80-07be85d359a6.png)
the icons broke
