### ISSUE TITLE
[Proposal] Connections Menu Re-order

### ISSUE THREAD

**Issue by Arion-Kun** [TakosThings/Metro-for-Discord#222]
**What are your changes?**
Have Connections be extended to be in 2 columns not just one.

**Why do you want to propose these changes?**

Having just 1 column causes unneeded scrolling.
![img](https://cdn.discordapp.com/attachments/826459638383640617/830073998154268703/DiscordCanary-Dawn-607-247-4f.png)

**Comment by Arion-Kun** [comment]
Additionally, any link you click on seems to go to the steam one

**Comment by TakosThings** [comment]
![image](https://user-images.githubusercontent.com/20344790/114191064-28dce080-998b-11eb-91c9-05e0788db269.png)
Pretty easy change, I'll put it through in the next build which will be shortly.

> Additionally, any link you click on seems to go to the steam one
Can't seem to replicate this
