### ISSUE TITLE
Make a website for changing colors

### ISSUE THREAD

**Issue by andrew071117** [TakosThings/Metro-for-Discord#226]
hi i think you need to make a website for changing colors for people who do not know css

**Comment by TakosThings** [comment]
Kind of related to #216 

I'm looking into it when I have the time and motivation.

All the steps for changing accent colours are in the [Setup Guide](https://github.com/TakosThings/Metro-for-Discord/wiki/Setup-Guide), and there's also a page with the [Windows 10 Accent Colours](https://github.com/TakosThings/Metro-for-Discord/wiki/Accent-Colours) with the numbers you need to change.

**Comment by maicol07** [comment]
Maybe also related to https://github.com/TakosThings/Metro-for-Discord/issues/203
