### ISSUE TITLE
overlapping icons

### ISSUE THREAD

**Issue by LucidNyxx** [TakosThings/Metro-for-Discord#229]
This happens when you click the home button, and the server or server folder below it always gets overlapped. But overall clean theme. It's my favorite one by far.
![Discord_IgM4BwV3qi](https://user-images.githubusercontent.com/80446279/117246779-102ce280-adf2-11eb-863e-c14ca42b095b.png)

**Comment by TakosThings** [comment]
Can't seem to replicate. Assuming you use BetterDiscord, do you have any other plugins or themes active?

**Comment by LucidNyxx** [comment]
Yes, i do have BetterDiscord. And I turned off all my plugins, and I only have your theme on.

**Comment by nicolastuttle** [comment]
I noticed this myself, been like that for a while. The bag renders behind my first server icon. Pretty sure it's tied to the [library tab that was removed](https://blog.discord.com/were-constantly-listening-to-your-feedback-and-working-to-improve-how-discord-feels-and-functions-676a5cb3ab63), but still appears if you own a game on Discord. Happy to add more info if needed.

**Comment by TakosThings** [comment]
> Pretty sure it's tied to the library tab

Yep, this is the problem. I'm afraid there's not much I can do to fix this unfortunately
