### ISSUE TITLE
Misplaced icons

### ISSUE THREAD

**Issue by nolemretaWxd** [TakosThings/Metro-for-Discord#230]
![image](https://user-images.githubusercontent.com/31414969/117699563-489f3880-b1c5-11eb-9dc5-ff5c4163e76e.png)

Language is English US

**Comment by andrew071117** [comment]
█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████
█░░░░░░░░░░░░░░█░░░░░░█████████░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░██████░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█
█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀░░░░████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█
█░░▄▀░░░░░░░░░░█░░▄▀░░█████████░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░▄▀▄▀░░████░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█
█░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░████░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░█████████
█░░▄▀░░░░░░░░░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░████░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█░░▄▀░░█████████░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█
█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█
█░░▄▀░░░░░░░░░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░████░░▄▀░░░░░░░░░░█░░░░░░░░░░▄▀░░█░░▄▀░░█████████░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░░░░░░░░░█
█░░▄▀░░█████████░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░██░░▄▀░░████░░▄▀░░█████████████████░░▄▀░░█░░▄▀░░█████████░░▄▀░░██░░▄▀░░█░░▄▀░░█████████░░▄▀░░█████████
█░░▄▀░░█████████░░▄▀░░░░░░░░░░█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░░░▄▀░░█░░▄▀░░░░▄▀▄▀░░████░░▄▀░░░░░░░░░░█░░░░░░░░░░▄▀░░█░░▄▀░░░░░░░░░░█░░▄▀░░██░░▄▀░░█░░▄▀░░█████████░░▄▀░░░░░░░░░░█
█░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀░░░░████░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀▄▀▄▀▄▀▄▀░░█░░▄▀░░██░░▄▀░░█░░▄▀░░█████████░░▄▀▄▀▄▀▄▀▄▀░░█
█░░░░░░█████████░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░██████░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░░░░░░░░░█░░░░░░██░░░░░░█░░░░░░█████████░░░░░░░░░░░░░░█
█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████

**Comment by andrew071117** [comment]
╱╱╱╱╱╱╱╱╭╮
╱╱╱╱╱╱╱╭╯╰╮
╭╮╭┳━━╮╰╮╭╋━━╮
┃╰╯┃┃━┫╱┃┃┃╭╮┃
┃┃┃┃┃━┫╱┃╰┫╰╯┃
╰┻┻┻━━╯╱╰━┻━━╯

**Comment by andrew071117** [comment]
╱╱╱╱╱╱╱╱╭╮
╱╱╱╱╱╱╱╱┃┃
╭━━┳━╮╭━╯┣━┳━━┳╮╭╮╭╮
┃╭╮┃╭╮┫╭╮┃╭┫┃━┫╰╯╰╯┃
┃╭╮┃┃┃┃╰╯┃┃┃┃━╋╮╭╮╭╯
╰╯╰┻╯╰┻━━┻╯╰━━╯╰╯╰╯

**Comment by andrew071117** [comment]
╱╱╱╱╱╱╱╱╭╮
╱╱╱╱╱╱╱╱┃┃
╭━━┳━╮╭━╯┣━┳━━┳╮╭╮╭╮
┃╭╮┃╭╮┫╭╮┃╭┫┃━┫╰╯╰╯┃
┃╭╮┃┃┃┃╰╯┃┃┃┃━╋╮╭╮╭╯
╰╯╰┻╯╰┻━━┻╯╰━━╯╰╯╰╯

**Comment by TakosThings** [comment]
@andrew071117 You'll be blocked if you keep that up.

**Comment by TakosThings** [comment]
Can't seem to replicate, I'll keep open for a little to see if anything pops up

**Comment by tryoutuser** [comment]
@nolemretaWxd is this because your discord window size too small?

**Comment by nolemretaWxd** [comment]
> @nolemretaWxd is this because your discord window size too small?

Maximized on 1080p is too small?

**Comment by tokiioKH** [comment]
Was this problem ever fixed? I am still getting this now.

**Comment by TakosThings** [comment]
Nope, I'm unable to replicate on any other computer

**Comment by tokiioKH** [comment]
Oh, okay then. Yeah, I am trying everything on Discord stable so I can see what triggers it. I turned off all my plugins and everything, but I still get the same thing.

**Comment by tokiioKH** [comment]
> ![image](https://user-images.githubusercontent.com/31414969/117699563-489f3880-b1c5-11eb-9dc5-ff5c4163e76e.png)
> 
> Language is English US

Did you figure out how to replicate it?

**Comment by tokiioKH** [comment]
> Nope, I'm unable to replicate on any other computer

I figured it out.

![RHBC1BIX61](https://user-images.githubusercontent.com/56203908/123010201-fb40ea00-d372-11eb-8d82-9fbc5929c2fc.gif)

**Comment by tokiioKH** [comment]
> ![image](https://user-images.githubusercontent.com/31414969/117699563-489f3880-b1c5-11eb-9dc5-ff5c4163e76e.png)
> 
> Language is English US

Turn off "show voice users"

**Comment by TakosThings** [comment]
Re-opening since this will be fixed in the next update (probably a little bit later today).
