### ISSUE TITLE
Lots of icons missing. Need to know new font version.

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#234]
**Before opening an issue**
* Make sure you have updated to the latest available version.
Just updated to v3.15.14 and BBD already on v1.1.0

**Describe the bug**
A lot of icons in settings are missing

**Steps to reproduce**
Visible after updating to latest version

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/118393451-7410a000-b669-11eb-8856-18e9a5860861.png)

![image](https://user-images.githubusercontent.com/35561383/118393455-7d017180-b669-11eb-9a9d-2c9646cbb09e.png)

![image](https://user-images.githubusercontent.com/35561383/118393461-87237000-b669-11eb-819a-53121df5b7aa.png)

**Comment by TakosThings** [comment]
It's just Discord changing the `aria-controls` tags again. I'll push a fix in a minute.

**Comment by tryoutuser** [comment]
big thanks!
