### ISSUE TITLE
GooseMod Support

### ISSUE THREAD

**Issue by CanadaHonk** [TakosThings/Metro-for-Discord#248]
**Is your feature request related to a problem? Please describe.**
Not related to any problems.

**Describe the solution you'd like**
Adding Metro for Discord to GooseMod's Store for people using it to be able to easily use the theme.

**Additional context**
Sorry for random issue, I'm the lead dev of [GooseMod](https://goosemod.com), new mod I started developing end of last year. A few users have requested this theme being added to it's store and this is the best way of asking / talking I've found. [This page gives some more info about porting](https://docs.goosemod.com/misc/ports.html#what-is-goosemod). Thanks!

**Comment by CanadaHonk** [comment]
To clarify, I essentially meant could I get your permission to add it to [it's store](https://store.goosemod.com).

**Comment by TakosThings** [comment]
Yeah, that's fine

**Comment by CanadaHonk** [comment]
Sorry for the delay, just to notify, it's now out in it's store. 
![image](https://user-images.githubusercontent.com/19228318/125121951-9ca69a80-e0ec-11eb-9420-2d4a272426bd.png)
