### ISSUE TITLE
Citador support

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#25]
While you're doing huge major rebuid because new discord classes, can you add support for Citador plugin on compact mode like this?

![screenshot](https://x0.at/PpW.jpg)

Thanks

**Comment by TakosThings** [comment]
Going to have to reject this for the time being. Writing and maintaining support for all the plugins is too much of a hassle. I _may_ revisit this when BetterDiscord v2 is released, but I can't make any promises.
