### ISSUE TITLE
BetterDiscord: Public server button and Plugin support for ReadAllNotificationsButton

### ISSUE THREAD

**Issue by CloudX713** [TakosThings/Metro-for-Discord#252]
Is it possible to fix without removing public and the read all plugin?
![Screenshot 2021-07-03 212530](https://user-images.githubusercontent.com/72802595/124364946-3ed60680-dc45-11eb-9157-8dd1f109c4c4.png)

**Comment by CloudX713** [comment]
Thank you!

**Comment by tryoutuser** [comment]
thank you for adding this one too!
