### ISSUE TITLE
RTC Control Space

### ISSUE THREAD

**Issue by CloudX713** [TakosThings/Metro-for-Discord#253]
When not in a call, theres a blank space, it could be filled up with something else.
![Screenshot 2021-07-03 212736](https://user-images.githubusercontent.com/72802595/124365004-8bb9dd00-dc45-11eb-8433-2dd129cfc938.png)

**Comment by TakosThings** [comment]
The RTC/account area has been a persistent issue for a while now since Discord often makes changes here. So the current solution will probably stay as it is for the foreseeable future.
