### ISSUE TITLE
Some Activity Spacing Off

### ISSUE THREAD

**Issue by LucidNyxx** [TakosThings/Metro-for-Discord#256]
I am not sure how this happened, but some of the spacing is off on certain things in user popouts for activity. 

![Discord_QuDEJYg8Oh](https://user-images.githubusercontent.com/80446279/125153451-9f16ed80-e108-11eb-9eca-54153eac7ee3.png)
![Discord_ZdmFnLNtVi](https://user-images.githubusercontent.com/80446279/125153453-9f16ed80-e108-11eb-8de3-94093a62bf3b.png)

**Comment by Social-Interactive** [comment]
[Problem remains after  3.16.0 Release]

**Comment by TakosThings** [comment]
It's like this even without the theme on, so for now I'll just leave this open and it'll probably just resolve itself soon.

**Comment by Social-Interactive** [comment]
> It's like this even without the theme on, so for now I'll just leave this open and it'll probably just resolve itself soon.

Found fix, but thanks (changed some code)
