### ISSUE TITLE
Using code from Metro-for-Discord by TakosThings.

### ISSUE THREAD

**Issue by CloudX713** [TakosThings/Metro-for-Discord#257]
Hello TakosThings.
I want to use your CSS Code (Theme for BetterDiscord) and change the Code and upload it privately to friends.
(Your name and Github Link will stay.)
This is a really nice  theme I want to customize and use in small groups.
Thank you

**Comment by TakosThings** [comment]
Yes, you're free to.

Short version of the license:
https://creativecommons.org/licenses/by-nc-sa/3.0/
> Share — copy and redistribute the material in any medium or format
> Adapt — remix, transform, and build upon the material
