### ISSUE TITLE
Member Counter

### ISSUE THREAD

**Issue by Social-Interactive** [TakosThings/Metro-for-Discord#259]
Hello,
could you please add support for the Member Counter Plugin?
https://betterdiscord.app/plugin/MemberCount
'
![Screenshot 2021-07-10 181208](https://user-images.githubusercontent.com/72802595/125169416-5ca5ed00-e1aa-11eb-9302-7e3802061955.png)

**Comment by tryoutuser** [comment]
thank you for adding this plugin support! finally after years of using it, gets own design.
