### ISSUE TITLE
Plugin repo notifications not floating

### ISSUE THREAD

**Issue by KaKi87** [TakosThings/Metro-for-Discord#263]
**Describe the bug**
Plugin repo notifications aren't floating above the app but consuming in-flow height space, therefore making bottom elements unreachable until closed.

**Steps to reproduce**
Wait for plugin repo notifications

**Screenshots**
![2021-07-15 21_47_46-Greenshot](https://user-images.githubusercontent.com/21284089/125862541-d605c0c7-30b3-4400-8e93-ca17fea21cea.png)

---
Thanks

**Comment by TakosThings** [comment]
Marking this wontfix.

This isn't specifically a theme issue and 'fixing' this wouldn't really matter since any solution implemented in the theme will just permanently cover something else.

Besides, these banners are meant to be actioned immediately, or you can just close them.

**Comment by KaKi87** [comment]
No other BD theme has that issue.
