### ISSUE TITLE
Theme Download

### ISSUE THREAD

**Issue by Social-Interactive** [TakosThings/Metro-for-Discord#266]
MetroForDiscord.theme.css: Could not be compiled.
    at Object.loadAddon (<anonymous>:4:191839)
    at Object.loadAddon (<anonymous>:4:234060)
    at FSWatcher.<anonymous> (<anonymous>:4:190100)

**Comment by TakosThings** [comment]
Cannot replicate this.

Try the following:
* Restart discord (close from system tray, relaunch)
* If still not resolved, redownload the theme from the [Releases](https://github.com/TakosThings/Metro-for-Discord/releases/tag/v3.16.2) page
