### ISSUE TITLE
A lot of icons missing in 3.16.2

### ISSUE THREAD

**Issue by herfavesenpai** [TakosThings/Metro-for-Discord#267]
User icon settings and top bar icons are missing.
![image](https://user-images.githubusercontent.com/10445573/126702221-8112edbf-6a8f-4b44-b4c8-c169fffcf2d1.png)

![image](https://user-images.githubusercontent.com/10445573/126702245-a1238747-9ee9-4751-938e-7ca7110f8a40.png)

**Comment by NicciZar** [comment]
Can confirm. Just downloaded the newest version
![image](https://user-images.githubusercontent.com/43537611/126809216-a05cdd78-b293-474a-a910-56d44d152fe7.png)

![image](https://user-images.githubusercontent.com/43537611/126809274-f43e8d1b-fd38-4438-ad38-308ae0f66fe8.png)

**Comment by Social-Interactive** [comment]
I modified the code from this Theme for my Server to give it to my users (CC)
I fixed it and added threads

**Comment by TakosThings** [comment]
This looks like it might be an A/B test of some kind, so we'll have to wait a bit. Try using a previous version (1.16.0) and see if works better for you.
