### ISSUE TITLE
Cannot scroll connected accounts on large profile pop up

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#268]
using BBD 1.2.0
theme version 3.16.2

**Describe the bug**
cannot scroll down to see connected accounts list. whether on my own profile pop up or some other user profiles. sometimes certain user is scrollable.

**Steps to reproduce**
open your own profile pop ups, the large detailed one from "view profile" small pop up in text chat list

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/127312062-664e903a-b8a1-4173-adbd-576516c39bef.png)

**Comment by TakosThings** [comment]
Currently can't replicate. Looks like an A/B test is going on, so leaving open for now

**Comment by TakosThings** [comment]
Closing, unable to replicate.
