### ISSUE TITLE
version 3.16.3 shows version 3.16.2

### ISSUE THREAD

**Issue by NicciZar** [TakosThings/Metro-for-Discord#270]
Its a minimal issue

After downloading the recent theme.css discord shows the version version 3.16.2

![image](https://user-images.githubusercontent.com/43537611/129402597-65eebef8-3c72-4601-b2a6-1dd202c80fcf.png)

![image](https://user-images.githubusercontent.com/43537611/129402623-c2aa73aa-6f6f-495a-9afd-ff58556c7b3b.png)

**Comment by TakosThings** [comment]
fixed
