### ISSUE TITLE
Server icons reverted to default after latest Discord update 

### ISSUE THREAD

**Issue by MrHugelberg** [TakosThings/Metro-for-Discord#279]
its pretty much the common spacing issue that happens every now and then. reported by biru-cs few weeks ago #276  

Description: After the latest Discord update the server icons reverted to default, just as if I had not applied any theme (they are also cut off due to the DM and group chat list).

Steps to reproduce: There are no steps. I just opened Discord and the issue was there from the start.

Screenshot:
![image](https://user-images.githubusercontent.com/25200709/139134831-907f47ef-b019-45ba-a7f1-13d66e48893e.png)

**Comment by MrHugelberg** [comment]
I am sorry, I think, it wasnt even your Theme.
Must be some other plugin wich caused it. I thought I disabled all before I reported, but I didn't apparantly.

**Comment by LucidNyxx** [comment]
> I am sorry, I think, it wasnt even your Theme. Must've been some other BD plugin wich caused it. I thought I disabled all before I reported, but I didn't apparantly.

By any chance did you fix this? I have the same problem and I disabled all my plugins.

**Comment by BrightsydeJacobDev** [comment]
> I am sorry, I think, it wasnt even your Theme. Must've been some other BD plugin wich caused it. I thought I disabled all before I reported, but I didn't apparantly.

Maybe it's must be related to PTB/Canary version or some plugins.

**Comment by TakosThings** [comment]
Reopening and pinning this issue for tracking.

If you're having an issue with the latest version of the theme (v3.16.9) try downgrading back to [v3.16.8](https://github.com/TakosThings/Metro-for-Discord/releases/tag/v3.16.8). Discord may have reverted the changes they made earlier.

**Comment by BrightsydeJacobDev** [comment]
Update: after my PC got BSOD for something something, Discord PTB updates to Ptb 103255 (ae3387d) and its broken, reverted to default while also having a new Status (#281) issues.

**Comment by BrightsydeJacobDev** [comment]
Update 2: Discord once again updates and fixed this issues on all of the version, except this minor issues (see #281):
![image](https://user-images.githubusercontent.com/60382442/139970462-1349204a-7eb2-40eb-85a4-f4cd1b6221b8.png)
