### ISSUE TITLE
[PTB] Status icon reverted to default [3.16.9]

### ISSUE THREAD

**Issue by BrightsydeJacobDev** [TakosThings/Metro-for-Discord#281]
**Describe the bug**
The user icon reverted to default, plus it's broke the option to select any Status, happen on PTB and Canary for now.

**Steps to reproduce**
Happened out of the box, doesn't matter which plugins you have.
Also, clicking on the icon does nothing.

**Screenshots**
![image](https://user-images.githubusercontent.com/60382442/139787300-d9383395-f1c0-4542-a3c4-be1d3ddf2e01.png)

![image](https://user-images.githubusercontent.com/60382442/139787266-7f3a7a9a-6d5d-4162-942b-4e2ebf8ba107.png)

UPDATE: This bug was somewhat changed now after a update fixes it, the button is working, but still wrong position:
![image](https://user-images.githubusercontent.com/60382442/139970521-9a3ed2c1-c67c-4153-af81-ab74e356dbed.png)

**Comment by BrightsydeJacobDev** [comment]
any updates? this bug is still there through.

**Comment by TakosThings** [comment]
Probably addressed in 3.16.10 (released yesterday) which just does away with the custom avatar positioning.

Unfortunately I can't really justify spending time on PTB or Canary. Usually any spare time I have is spent on the Fluent theme instead.

**Comment by tryoutuser** [comment]
That is a nice touch on stable i gotta say. great changes to look at.

**Comment by BrightsydeJacobDev** [comment]
checked on both stable/ptb and its mostly fixed entirely.
