### ISSUE TITLE
Search popup elements unthemed

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#284]
**Describe the bug**
Search popup suggestion elements seems reverted or unthemed back to discord's default. You can see discord default theme shade.

I've seen this since 3.16.9 and still on 3.16.10.

Here is my version details:
![image](https://user-images.githubusercontent.com/35561383/142736511-cb956fb5-6231-4f7f-9250-bfbcdfab4c4a.png)

**Steps to reproduce**
Open search popup / Ctrl+F.

**Screenshots**
![image](https://user-images.githubusercontent.com/35561383/142736459-0bf96355-fe96-44fc-b8dc-0304193e60ce.png)

**Comment by BrightsydeJacobDev** [comment]
same here, all appeared on stable and ptb.
