### ISSUE TITLE
Completely broken in newer version of Discord/BetterDiscord

### ISSUE THREAD

**Issue by BrightsydeJacobDev** [TakosThings/Metro-for-Discord#286]
![Screenshot_6](https://user-images.githubusercontent.com/60382442/148877419-a64e4f32-7939-421d-98c1-847e6fa80d2c.png)

The theme seems to be broken again for some reason, only fonts changing, but anything else like themes does not change.
Reinstalling BetterDiscord didnt even help. Some others themes (as long if its simple) works fine but slightly broken, some others suffered the same as Metro for Discord.

Metro for Discord: (slightly modified) 3.16.11 (latest)
OS: Windows 7 (64-bit) with Segoe UI Emoji 1.33 (Windows 11 version), HoloLens MDL2 2.02
Discord: Stable 110451 (c233a73), Host 1.0.9003.

**Comment by NanKillTV** [comment]
Same issue
![image](https://user-images.githubusercontent.com/72297072/148892137-102f9f9e-f55b-4933-9e1c-a963a661bc53.png)

**Comment by TakosThings** [comment]
Sadly they've done a full class reroll so at this stage I'm not sure I'll continue working on this theme in favour of working on Fluent Discord.

I've just put up a pre-release on the [Fluent Discord repo](https://github.com/TakosThings/Fluent-Discord/releases/latest).

**Comment by tryoutuser** [comment]
Same here. oh no sad :( this is the best theme i've had ever since i found betterdiscord.
