### ISSUE TITLE
Shift + Enter in chat causes visual error.

### ISSUE THREAD

**Issue by iKatt** [TakosThings/Metro-for-Discord#30]
The text is far too spaced to the right, as shown below
![image](https://user-images.githubusercontent.com/10321978/39955664-5831f00c-5616-11e8-8f09-358810aa2a9e.png)

**Comment by TakosThings** [comment]
This is pretty much intended behaviour, though the indenting could be reduced.

**Comment by iKatt** [comment]
I personally would like to see the indentation to be reduced slightly, to the start of the message on the first layer.
