### ISSUE TITLE
i am using the translater plugin

### ISSUE THREAD

**Issue by gco360** [TakosThings/Metro-for-Discord#33]
you need to move the uploader button because it comes under the translator plugin 
![screenshot_1](https://user-images.githubusercontent.com/31587917/40294348-cea426e6-5cf2-11e8-9d5f-23c971db39c7.png)

**Comment by TakosThings** [comment]
I've addressed this previously in #25, at this time I won't be maintaining support for plugins. I'll revisit this when BetterDiscord v2 is released.
