### ISSUE TITLE
@tting popup changed back, again.

### ISSUE THREAD

**Issue by iKatt** [TakosThings/Metro-for-Discord#38]
Where the issue can be located:
![image](https://user-images.githubusercontent.com/10321978/41075872-0b01a566-6a52-11e8-9ca4-742c0325b5d8.png)
![image](https://user-images.githubusercontent.com/10321978/41075874-0d61d9f2-6a52-11e8-905b-5809d2f2a8a0.png)

**Comment by TakosThings** [comment]
Trust Discord to needlessly change shit every second week

**Comment by iKatt** [comment]
Sounds about right.
