### ISSUE TITLE
Friends tab

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Metro-for-Discord#40]

**Comment by tryoutuser** [comment]
Some right click context menu on:
1) embedded image preview from link
2) servers list
3) channels list
gone far away out of it's place.

**Comment by TakosThings** [comment]
> Try not to report multiple unrelated issues in the same submission, open new issues for them instead  

I cannot replicate any issues with context menus

**Comment by TakosThings** [comment]
Setting the carousel to full-width seriously degrades image quality  
[Preview](https://cdn.discordapp.com/game-assets/356888453796986880/1f162572c3123655e42c615b18074ff3.webp?size=64)
