### ISSUE TITLE
2018-07-25 Update

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Metro-for-Discord#44]
- [x] Chat
- [x] Recent mentions popout - Mentions are unstyled
- [x] Search popout - out of position
- [x] Chat message popout

**Comment by Starwort** [comment]
(not in post currently, adding):
- [ ] Fix code block lacking type identification banner
![Current](https://user-images.githubusercontent.com/16487249/43203840-308fb134-9017-11e8-8b49-b2b381707c09.png)
should be like
![Old](https://user-images.githubusercontent.com/16487249/43204023-b82103be-9017-11e8-8379-4467842c93b5.png)
