### ISSUE TITLE
Code blocks lacking type banner

### ISSUE THREAD

**Issue by Starwort** [TakosThings/Metro-for-Discord#45]
- Theme downloaded today, 5 minutes ago (3.9.3)
- BetterDiscord edition of Metro
Code blocks no longer have the 'type' banner I'm used to. (Second picture is from salvaged screenshot of old banner, hence quality)
![Current](https://user-images.githubusercontent.com/16487249/43203840-308fb134-9017-11e8-8b49-b2b381707c09.png)
![Old](https://user-images.githubusercontent.com/16487249/43204023-b82103be-9017-11e8-8379-4467842c93b5.png)

**Comment by TakosThings** [comment]
See #44

**Comment by Starwort** [comment]
This isn't mentioned in that post

**Comment by Starwort** [comment]
But thanks for the quick response
