### ISSUE TITLE
Unread msg in server not showing

### ISSUE THREAD

**Issue by GRIMMboi** [TakosThings/Metro-for-Discord#5]
When there's a server with an unread msg in it the box isn't there. That's the best way I know how to word it idk. 
https://gyazo.com/5ac6fe9c971952a3143035ce4f8d238f 
that ^ the blue box isn't there.
I hope I worded this good enough for you to understand. XD

**Comment by GRIMMboi** [comment]
dont hate me lol

**Comment by TakosThings** [comment]
![](https://i.imgur.com/ATZ6HHb.png)
The unread messages bar?

**Comment by TakosThings** [comment]
Is your `--accent` colour defined correctly in root?  
By default it's `--accent: #0072C6;`

**Comment by GRIMMboi** [comment]
i usually change it to  --accent: ##AC193D; but i grabbed the default and im seeing if it does the same thing

**Comment by TakosThings** [comment]
You should only have one `#` symbol.

**Comment by GRIMMboi** [comment]
really
opps

**Comment by GRIMMboi** [comment]
i done goofed
