### ISSUE TITLE
User Settings position is changed

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#57]
The user settings icon has moved

![image](https://user-images.githubusercontent.com/36117192/46838147-976e6280-cd7d-11e8-9de0-aece6c8790a6.png)
![image](https://user-images.githubusercontent.com/36117192/46838150-99d0bc80-cd7d-11e8-9309-cee3c1228bc5.png)

**Comment by TakosThings** [comment]
I can't seem to replicate this. I'm guessing you might have a BD plugin which is causing this to happen. Try enabling/disabling each one to isolate which one is the cause.

**Comment by silent** [comment]
Nope, it fixed itself after the latest update on Discord. All good :)
