### ISSUE TITLE
2018-10-17 Update

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Metro-for-Discord#58]
* **Settings Button Out of Position**
This issue seems to occur at random, and is usually resolved with a client restart. 

* **Games Shop**
For various reasons, I won't be working on this right now. Disable the games tab in Settings > Appearance > un-toggle 'Show games tab'

**Comment by silent** [comment]
I figured the settings button could have been due to a plugin I was using but I am glad that is confirmed.
