### ISSUE TITLE
[Feature request] Change the highlight coloring for text channels or servers

### ISSUE THREAD

**Issue by ab996abeed** [TakosThings/Metro-for-Discord#6]
I find that highlighting colors for text channels are inconsistent with the ones for servers, specifically, the color for a server with unread messages is --accent and the currently selected server color is white, however the text channel colors for unread is white and the current channel is --accent. I find this confusing and inconsistent.
In my opinion, it would make more sense for the respective highlighting colors to represent the same thing (accent for unread messages, white for current channel/server). At least an alternative version with consistent coloring would be much appreciated.

**Comment by TakosThings** [comment]
Changed in v2.22.6
