### ISSUE TITLE
Theme seems a bit broken on ubuntu

### ISSUE THREAD

**Issue by RaspberryKitty1** [TakosThings/Metro-for-Discord#63]
im using 3.9.13 on betterdiscord

![image](https://user-images.githubusercontent.com/28585042/47534944-4a16e880-d887-11e8-848a-8c4a93cc5ed5.png)

**Comment by TakosThings** [comment]
As described in #57 and #58 it's likely that this is an intermittent issue which can be resolved with a client restart. If this issue is specifically an Ubuntu/Linux issue there won't be much I can do about it.

**Comment by RaspberryKitty1** [comment]
hhm I disabled all my plugins and reloaded the theme same results so it must be an issue with Ubuntu/Linux. thanks for the help anyways :3
