### ISSUE TITLE
Search bar isn't themed

### ISSUE THREAD

**Issue by CtrlShiftEscape** [TakosThings/Metro-for-Discord#71]
Discord changed their class again
![discord_2019-01-12_12-11-17](https://user-images.githubusercontent.com/36315896/51072078-a2c67800-1663-11e9-941a-185998f76186.png)
![image](https://user-images.githubusercontent.com/36315896/51072178-2af94d00-1665-11e9-923c-cdf0c49e8833.png)

**Comment by tryoutuser** [comment]
I've experienced the same, hope Tako will fix these.
