### ISSUE TITLE
Online friends count in the guilds list.

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#76]
After removing the lines to show the Friends Online, it's not spaced properly nor is the text white:
![image](https://user-images.githubusercontent.com/36117192/53282336-ec42c200-36fb-11e9-81c1-f26d4d2df97a.png)

Before:
![image](https://user-images.githubusercontent.com/36117192/53282884-d6d19600-3703-11e9-853d-5111e542ebc6.png)

**Comment by TakosThings** [comment]
This is _somewhat_ mitigated in 3.10.3. Release coming shortly...
