### ISSUE TITLE
New bugs due to recent discord version

### ISSUE THREAD

**Issue by tryoutuser** [TakosThings/Metro-for-Discord#80]
New major discord version just pushed few minutes ago and these are what i spot as broken :

![image](https://user-images.githubusercontent.com/35561383/54222744-9a39d300-4528-11e9-9d2e-74a5a5958a03.png)

Annoying new server discovery appears.

![image](https://user-images.githubusercontent.com/35561383/54222808-b6d60b00-4528-11e9-9bc9-098d552d7b6d.png)

"Add server" tooltip, and outage guild icon went out of proportion.

**Comment by silent** [comment]
`.container-11WMXy { display: none }`
Will fix that.

Also, seems like typing is far off to the right: 
![image](https://user-images.githubusercontent.com/36117192/54240113-2a592780-44eb-11e9-91ab-60aeaabf3e7e.png)

**Comment by tryoutuser** [comment]
I don't see anything wrong with guild call indicators/buttons, so that's all i guess.

**Comment by Dajova** [comment]
Yeah, there seems to be a issue with server discovery icon when you have more than 10 servers. Seems to be locked based on location on discord and not by the list itself. 

![image](https://i.imgur.com/QggLEAb.png)
