### ISSUE TITLE
Home and DM buttons don't work, and GIF button disappears

### ISSUE THREAD

**Issue by sVortexHD** [TakosThings/Metro-for-Discord#83]
Home and DM buttons don't work, and GIF button disappears

**Comment by TakosThings** [comment]
I've edited your original post to condense the title, and to make it easier to read. Generally try to keep the title to a short description of the issue and the have further details in the body.

I cannot reproduce any issues with the Home or DM buttons.

The GIF button in the chat box was removed intentionally. This is noted in CHANGELOG.md and was discussed briefly in [#77](https://github.com/TakosThings/Metro-for-Discord/issues/77#issuecomment-471848871)

**Comment by silent** [comment]
Make sure you are using the updated Metro For Discord, I am unable to reproduce this.

**Comment by tryoutuser** [comment]
Tako please add the lines for restoring gif button around user options or "remove this" area despite it won't be designed, I kinda don't really care about its dialog/window not themed, but at least it's there.

**Comment by sVortexHD** [comment]
it is the latest version and idk. reproducing the gif button disappearing just takes you to enable the theme.

**Comment by silent** [comment]
> Tako please add the lines for restoring gif button around user options or "remove this" area despite it won't be designed, I kinda don't really care about its dialog/window not themed, but at least it's there.

If you want to have the gif button back just remove these lines and be done with it
`    .theme-dark .chat-3bRxxu form div[class*="channelTextArea-"] .buttons-205you .buttonWrapper-1ZmCpA {
      display: none; }
    .theme-dark .chat-3bRxxu form div[class*="channelTextArea-"] .buttons-205you .buttonContainer-21MN7J {
      display: none; }`
