### ISSUE TITLE
Context menu clips under titlebar if too many items are displayed, on certain resolutions

### ISSUE THREAD

**Issue by sVortexHD** [TakosThings/Metro-for-Discord#87]
i dont even know how to explain it correctly, but it only happens with the theme on so im guessing its metro's fault. https://i.imgur.com/eT57XE7.png
here's a ss of what happens, the right click list of options is too long for a 1080 long window i guess, so it hides part of the options under the window bar of discord.

**Comment by silent** [comment]
I have a plugin that fixes that problem for me.
