### ISSUE TITLE
Settings/Mic/Etc changed

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#92]
**Describe the bug**
After restarting discord and applying the latest update of the theme I noticed the image below.

**Screenshots**
![image](https://user-images.githubusercontent.com/36117192/59546696-0c3f0100-8ef8-11e9-9827-8daf8ce3c1fb.png)

**Comment by integralfx** [comment]
I had the same issue, but it's fixed in 3.10.10.

**Comment by TakosThings** [comment]
This was fixed in 3.10.10.

Can't replicate this issue with the avatar though.

**Comment by silent** [comment]
Well if you noticed I posted this during 3.10.9, not 3.10.10 so this is now fixed.
