### ISSUE TITLE
[3.11.0] Prerelease 1 Available

### ISSUE THREAD

**Issue by TakosThings** [TakosThings/Metro-for-Discord#94]
Prerelease 1 of v3.11.0 is now available for testing in the 3.11.0 branch.

Note that this version is still work in progress.

**What are your changes?**
```markdown
#### 3.11.0
* **Clean Up**
  * Remove `/core/_userstyle_options.scss` - Unused
  * Remove `/home/games` - Out of scope
  * Rename `/modal/_deprecated_new_server.scss` to `/modal/_new_server.scss`
  * Remove `/primary/members/_loading.scss` - Unused
  * Tidy `/vendor/_hljs_monokai.scss`
  * Clean `/icons/_core.scss`
* **Enchancements**
  * Remove guild level icon. 'Official' or 'partnered' sever icons will still be shown
  * Remove background from server name menu to expose the server banner
  * Set more agressive gradient on server banner so it blends with our background-color
  * Server discovery
  * Update Add Friend page
  * Add/Join server modal
  * Added variable for Segoe UI MDL2 Assets font
  * Added icons for menu items in Client/Server/Channel settings
  * Rewrite forms and inputs, and moved to own scss files
  * Convert to use MDL icons in most places
* **Fixes**
  * Status circles will now use theme status colours
  * Remove borders or box shadows from status circles
  * Emoji picker search
  * Show selected menu item pill in client/server settings
  * Unmute and Undeafen buttons still appeared when not connected to a voice channel
```

Please report issues directly related to v3.11.0 here.

**Comment by TakosThings** [comment]
**Misc issues**  
* Black text in RTC connection popout 

Also not noted in the above changelog:
* Return to channel icon removed from RTC ping meter (due to functionality change)

**Comment by silent** [comment]
Disconnect icon is missing
![image](https://user-images.githubusercontent.com/36117192/60331156-a3c13c80-9959-11e9-92ac-2825f513437a.png)

As well as an unnecessary space between the undeafen and connection icon.

**Comment by TakosThings** [comment]
Possible AB testing, I have this Soice Status button instead with connection info moved to the ping indicator.

![image](https://user-images.githubusercontent.com/20344790/60331681-5f26b700-99d4-11e9-9468-19e9682e6900.png)

**Comment by TakosThings** [comment]
On Issue #93 - This is turning out to be a tricky one as the bug has come and gone multiple times now. For now I'm marking it as 'fixed'

**Comment by TakosThings** [comment]
Channels account box reverted to default
