### ISSUE TITLE
Voice/Setting Modal has default theme

### ISSUE THREAD

**Issue by silent** [TakosThings/Metro-for-Discord#98]
**Describe the bug**
 Voice and settings modal has the default theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/36117192/61160883-058bb580-a4c7-11e9-9956-7aff32e0dffc.png)

**Comment by TakosThings** [comment]
Marking as 'ongoing'.  
Unfortunately this is a 'works for me' bug.

**Comment by silent** [comment]
Randomly fixed itself today. So I don't know.
